apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-credentials-service-account
  namespace: default
secrets:
  - name: docker-registry-credentials
imagePullSecrets:
  - name: docker-registry-credentials